name: Merge PR into student branch

on:
  pull_request_target:
    types: [labeled]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  merge-to-username-branch:
    name: Merge PR into student's branch
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      SEMESTER_PREFIX: "2025-fall"

    if: github.event.label.name == 'graded' # only runs when labeled manually

    steps:
      - name: Get PR info
        id: prinfo
        run: |
          echo "username=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "head_ref=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          echo "head_repo=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT

      - name: Checkout main to base new branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.REPO_PUSH_TOKEN }}

      - name: Create and push new base branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

          BRANCH="${{ env.SEMESTER_PREFIX }}-${{ steps.prinfo.outputs.username }}"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"

      - name: Change PR base branch
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const username = "${{ steps.prinfo.outputs.username }}";
            const newBase = `${process.env.SEMESTER_PREFIX}-${username}`;

            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              base: newBase
            });

      - name: Fetch PR head from fork and force-push into new branch
        run: |
          git remote add fork https://github.com/${{ steps.prinfo.outputs.head_repo }}.git
          git fetch fork ${{ steps.prinfo.outputs.head_ref }}

          BRANCH="${{ env.SEMESTER_PREFIX }}-${{ steps.prinfo.outputs.username }}"
          git push origin fork/${{ steps.prinfo.outputs.head_ref }}:refs/heads/$BRANCH --force
